### ISSUE TITLE
Encoding returns hex values

### ISSUE THREAD

**Issue by MkHunter** [lloyd334/twitch-listener#3]
When listening to multi-lingual (RUS,JP) twitch channels sometimes messages are displayed as follow: "\xd0\xb1\xd1\x82\xd0\xb2"

**Comment by oliver-lloyd** [comment]
Noted, looks like it just needs some utf-8 decoding.

**Comment by oliver-lloyd** [comment]
Had a pop at solving this yesterday, turns out it is a non-trivial fix. I will come back to this

**Comment by oliver-lloyd** [comment]
Fixed in 1.2.1
